### ISSUE TITLE
Idea: Turn this into a Template Repository

### ISSUE THREAD

**Issue by JakeChampion** [fastly/compute-starter-kit-rust-default#25]
Howdy 👋

First off, this is a great starter kit, thank you for creating and updating it.

I was thinking it might be simpler/easier for people to use if you turned on the Template Repository feature.

The features enables people to quickly create a new repository with the contents of the starter kit.

Here is what the button looks like when viewing a Template Repository.
![screenshot of the google eleventy-high-performance-blog template repository](https://user-images.githubusercontent.com/1569131/104971302-4af74000-59e6-11eb-8279-1cf481cc153f.png)

To turn on the template feature you tick a box in the [main settings page](https://github.com/fastly/compute-starter-kit-rust-default/settings).

![screenshot of the repository main settings page](https://user-images.githubusercontent.com/1569131/104971290-3dda5100-59e6-11eb-92cd-344ea2c8f7d8.png)

I've forked this repository and turned it into a template repository for you to have a look at and try out pressing the "Use this template" button -- https://github.com/JakeChampion/compute-starter-kit-rust-default

**Comment by kailan** [comment]
Hey @JakeChampion, this is a great idea and I had thought of the same myself. Unfortunately, part of the process of creating a new C@E service is the initialization of a service on the Fastly API, which happens when you run `fastly compute init`. It is possible that extra steps could be added to this command in the future too.

For this reason I would encourage customers to use `fastly compute init --from=<repo-url>`, rather than cloning template repositories directly.

**Comment by kailan** [comment]
Hi Jake, hope you are keeping well. We recently updated the Fastly CLI to move service initialisation to the first execution of `compute deploy`, so I have now made this a template repository. Thanks for the suggestion!
